# Generated by Django 4.1.3 on 2022-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[(None, 'Choice type of article'), ('a', 'Article Common'), ('t', 'Tech Article')], default='a', max_length=1),
        ),
    ]
