# Generated by Django 4.1.3 on 2022-11-26 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=250, verbose_name='Brand Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('location', models.TextField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='Profile')),
                ('url_company', models.URLField(blank=True, null=True, verbose_name='Company Url')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel')),
                ('email', models.EmailField(max_length=250)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, null=True, size=None, verbose_name='Products')),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, null=True, size=None, verbose_name='Services')),
                ('webclick_counter', models.SmallIntegerField(default=0, verbose_name='Manufacture counter')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='readers_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Readers counter'),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('location', models.TextField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='Profile')),
                ('url_distributor', models.URLField(blank=True, null=True, verbose_name='Distributor Url')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel')),
                ('email', models.EmailField(max_length=250)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, null=True, size=None, verbose_name='Products Dist')),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, null=True, size=None, verbose_name='Services Dist')),
                ('webclick_counter', models.SmallIntegerField(default=0, verbose_name='Distributor counter')),
                ('manufactories', models.ManyToManyField(to='content.manufactor')),
            ],
        ),
    ]
