# Generated by Django 4.1.3 on 2022-11-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_manufactor_article_readers_counter_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='my_contact',
            field=models.JSONField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='manufactor',
            name='distributors',
            field=models.ManyToManyField(to='content.distributor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='readers_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='webclick_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='webclick_counter',
            field=models.SmallIntegerField(default=0, verbose_name='Count'),
        ),
    ]
