# Generated by Django 4.1.3 on 2022-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_distributor_my_contact_manufactor_distributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/distributor', verbose_name='Brand Image'),
        ),
        migrations.AddField(
            model_name='manufactor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/manufactor', verbose_name='Brand Image'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='manufactories',
            field=models.ManyToManyField(blank=True, null=True, to='content.manufactor'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='distributors',
            field=models.ManyToManyField(blank=True, null=True, to='content.distributor'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
