# Generated by Django 4.1.3 on 2022-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_distributor_image_manufactor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='my_contact',
            field=models.JSONField(blank=True, null=True, verbose_name='My Contact'),
        ),
    ]
