# Generated by Django 4.1.3 on 2022-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_distributor_my_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/static/media', verbose_name='Image main'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='content/static/media', verbose_name='Image for mobile'),
        ),
    ]
