# Generated by Django 4.1.3 on 2022-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_article_image_alter_article_image_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image main'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image for mobile'),
        ),
    ]
