# Generated by Django 4.1.3 on 2023-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index_page',
            field=models.BooleanField(default=False, verbose_name='Main page'),
        ),
    ]
