# Generated by Django 4.1.3 on 2023-08-23 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_article_index_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, db_index=True, default=list, null=True, size=None, verbose_name='Topics')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(to='content.topic'),
        ),
    ]
