# Generated by Django 4.1.3 on 2023-10-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timetoread',
            field=models.CharField(blank=True, default='3min', max_length=20, null=True, verbose_name='timetoread'),
        ),
    ]
