# Generated by Django 4.1.3 on 2023-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_article_timetoread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='content/static/media/', verbose_name='Image for mobile'),
        ),
    ]
